input_data:
  file1: "../data/raw/StressLevelDataset.csv"
  file2: "../data/raw/Stress_Dataset.csv"

output_data:
  file1: "../data/clean/file1.csv"
  file2: "../data/clean/file2.csv"
  file3: "../data/clean/file3.csv"
  file4: "../data/clean/file4.csv"
  fig1: "../figures/feature_distributions.png"
  fig2: "../figures/stress_level_distribution.png"
  fig3: "../figures/correlation_matrix.png"
  fig4: "../figures/stress_correlations.png"
  fig5: "../figures/feature_vs_stress_boxplots.png"
  fig6: "../figures/outlier_percentages.png"
  fig7: "../figures/mutual_information_scores.png"
  fig8: "../figures/pca_analysis.png"
  fig9: "../figures/risk_signal_strength.png"
